set nocompatible           " You want Vim, not vi. We set it explicitely to make our position clear!

syntax on                  " Enable syntax highlighting.
filetype plugin indent off " Load plugins according to detected filetype.

set autoindent             " Indent according to previous line.
set expandtab              " Use spaces instead of tabs.
set tabstop     =4
set softtabstop =4         " Tab key indents by 4 spaces.
set shiftwidth  =4         " >> indents by 4 spaces.
set shiftround             " >> indents to next multiple of 'shiftwidth'.

set showmode               " Show current mode in command-line.
set showcmd                " Show already typed keys when more are expected.

set incsearch              " Highlight while searching with / or ?.
set hlsearch               " Keep matches highlighted.

set splitbelow             " Open new windows below the current window.
set splitright             " Open new windows right of the current window.

set cursorline             " Find the current line quickly.
set wrapscan               " Searches wrap around end-of-file.
set report      =0         " Always report changed lines.
set synmaxcol   =200       " Only highlight the first 200 columns.

set relativenumber number
set nowrap
set updatetime=500

" Put all temporary files under the same directory.
set nobackup
set nowritebackup
set undodir     =$HOME/.config/vim/undo/
set directory   =$HOME/.config/vim/swap/
set viewdir     =$HOME/.config/vim/view/
set backupdir   =$HOME/.config/vim/backup/
set updatecount =100
set viminfo     ='100,n$HOME/.config/vim/info/viminfo

colorscheme catppuccin_mocha

" set highlight to 500ms
let g:highlightedyank_highlight_duration = 500

nnoremap cw ciw
nnoremap yw yiw
nnoremap dw diw
nnoremap vw viw

